// All on-screen copy lives here so fonts can be preloaded for exactly these glyphs.
export const S = {
  intro: {
    l1: '抬头看见的每一束星光',
    l2: '都是一封来自过去的信',
    l3: '宇宙，究竟有多大？',
    title: '宇宙',
    titleEn: 'THE UNIVERSE',
    tagline: '从地球出发，飞向时间的起点',
  },
  earth: {
    kicker: '第一站',
    title: '地球',
    en: 'EARTH',
    f1: '直径 {12,742} 公里',
    f2: '光，1 秒可以绕地球 {7.5} 圈',
    moon: '月球',
    f3: '距离地球 {38.4 万} 公里',
    f4: '光，也要走 {1.3} 秒',
  },
  sun: {
    kicker: '第二站',
    title: '太阳',
    en: 'THE SUN',
    earthTag: '这是地球',
    statLabel: '太阳的体积，能装下',
    statUnit: '个地球',
    f1: '核心温度 {1500 万} ℃',
    f2: '每秒把 {400 万吨} 物质化为光和热',
    f3: '它的光抵达地球，需要 {8 分 20 秒}',
  },
  solar: {
    kicker: '第三站',
    title: '太阳系',
    en: 'SOLAR SYSTEM',
    planets: ['水星', '金星', '地球', '火星', '木星', '土星', '天王星', '海王星'],
    f1: '八颗行星，在引力中环舞',
    f2: '光从太阳到海王星，要走 {4 小时}',
    oort: '奥尔特云 · 太阳系的边疆',
    f3: '人类飞得最远的探测器「旅行者 1 号」',
    f4: '已飞行 {49 年}，抵达这里还需 {300 年}',
  },
  stars: {
    kicker: '第四站',
    title: '恒星',
    en: 'STARS',
    names: ['太阳', '天狼星 A', '北河三', '大角星', '参宿七', '参宿四', '史蒂文森 2-18'],
    ratios: ['1', '1.7', '8.8', '25', '79', '约 760', '约 2150'],
    radiusLabel: '半径 × ',
    f1: '如果把它放在太阳的位置',
    f2: '它的表面，将越过 {土星轨道}',
    saturn: '土星轨道',
    f3: '而巨星的一生，会以最壮烈的方式落幕',
    nova: '超新星爆发',
    novaEn: 'SUPERNOVA',
    f4: '一瞬间的光芒，亮过整个星系',
    f5: '你血液里的铁，就锻造于恒星的死亡',
  },
  blackhole: {
    pre: '而最沉重的恒星，会坍缩成——',
    title: '黑洞',
    en: 'BLACK HOLE',
    f1: '引力强大到，连光都无法逃脱',
    f2: 'M87* · 质量是太阳的 {65 亿} 倍',
    f3: '2019 年，人类第一次拍到黑洞的影子',
    f4: '银河系的中心，也藏着一个——{人马座 A*}',
  },
  milky: {
    kicker: '第五站',
    title: '银河系',
    en: 'THE MILKY WAY',
    f1: '{1000 – 4000 亿} 颗恒星',
    f2: '直径约 {10 万} 光年',
    here: '你在这里',
    f3: '太阳绕银心一圈，需要 {2.3 亿年}',
    f4: '上一次在这个位置时，恐龙刚刚登场',
    andromeda: '仙女座星系',
    f5: '正以每秒 {110 公里} 的速度向我们靠近',
  },
  web: {
    kicker: '第六站',
    title: '宇宙网',
    en: 'COSMIC WEB',
    f1: '这里的每一个光点，都是一个星系',
    f2: '可观测宇宙中，有 {数千亿} 个星系',
    f3: '直径 {930 亿} 光年',
    f4: '现在，让时间倒流——',
  },
  bang: {
    f0: '{138 亿} 年前',
    f1: '可观测宇宙的一切，都挤在比原子还小的空间里',
    title: '大爆炸',
    en: 'THE BIG BANG',
    f2: '空间、时间、物质与能量，在这一刻诞生',
    f3: '{38 万} 年后，宇宙第一次变得透明',
    cmb: '宇宙微波背景辐射 · 最古老的光',
    f4: '{1 亿} 多年后，第一代恒星点亮了黑暗',
  },
  finale: {
    f1: '{138 亿} 年后',
    f2: '在一颗普通恒星旁的蓝色星球上',
    f3: '星尘聚成了会仰望星空的生命',
    f4: '你身体里的碳、氧、铁，都曾在恒星中锻造',
    q1: '我们，是宇宙认识自己的方式',
    q2: '—— 卡尔 · 萨根',
    title: '宇宙',
    en: 'THE UNIVERSE',
    end: '我们来自星辰，也终将望向星辰',
  },
  hud: {
    scale: '尺度',
    light: '光行时',
    units: ['秒', '分钟', '小时', '天', '年', '万年', '亿年'],
  },
};

const collect = (v: unknown): string =>
  typeof v === 'string' ? v : Array.isArray(v) ? v.map(collect).join('') : typeof v === 'object' && v ? Object.values(v).map(collect).join('') : '';

export const ALL_TEXT = collect(S);
